# Generated by Django 5.2.4 on 2026-02-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_artist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('artist', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'city')},
        ),
    ]
