# Generated by Django 5.2.4 on 2026-02-02 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tourplan_optimizationrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdate',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour'),
        ),
    ]
