# Generated by Django 5.2.4 on 2026-02-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tourdate_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
