# Generated by Django 5.2.4 on 2026-02-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_tourdate_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGroupVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.venue')),
            ],
            options={
                'unique_together': {('tour', 'venue')},
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='tour_groups', through='tours.TourGroupVenue', to='tours.venue'),
        ),
    ]
